In [37]:
import pandas as pd

school_data = pd.read_csv(r"C:\Users\lealr\OneDrive\DU Bootcamp\Pandas and Jupyter\Pandas-Challenge\schools_complete.csv")
student_data = pd.read_csv(r"C:\Users\lealr\OneDrive\DU Bootcamp\Pandas and Jupyter\Pandas-Challenge\students_complete.csv")

,Student ID,student_name,gender,grade,school_name,reading_score,math_score
0,0,Paul Bradley,M,9th,Huang High School,66,79
1,1,Victor Smith,M,12th,Huang High School,94,61
2,2,Kevin Rodriguez,M,12th,Huang High School,90,60
3,3,Dr. Richard Scott,M,12th,Huang High School,67,58
4,4,Bonnie Ray,F,9th,Huang High School,97,84

In [314]:
school_complete = pd.merge(student_data, school_data, how="left", on=["school_name", "school_name"])
school_complete.head()

,Student ID,student_name,gender,grade,school_name,reading_score,math_score,School ID,type,size,budget
0,0,Paul Bradley,M,9th,Huang High School,66,79,0,District,2917,1910635
1,1,Victor Smith,M,12th,Huang High School,94,61,0,District,2917,1910635
2,2,Kevin Rodriguez,M,12th,Huang High School,90,60,0,District,2917,1910635
3,3,Dr. Richard Scott,M,12th,Huang High School,67,58,0,District,2917,1910635
4,4,Bonnie Ray,F,9th,Huang High School,97,84,0,District,2917,1910635

In [27]:
# Counting the total number of unique schools
school_count = school_complete['school_name'].nunique()
print(school_count)

15

In [30]:
# Total number of students
student_count = school_complete['student_name'].count()
print(student_count)

39170

In [36]:
# The total budget
total_budget = school_data['budget'].sum()
print("$", total_budget)

$ 24649428

In [42]:
# Average math score
average_math_score = school_complete['math_score'].mean()
print(average_math_score)

# Average reading score
average_reading_score = school_complete['reading_score'].mean()
print(average_reading_score)

78.98537145774827
81.87784018381414

In [60]:
# Percentage of students passing math
passing_math = school_complete[(school_complete['math_score'] >= 70)].count()["student_name"]
print("Number of students passing math:", passing_math)

passing_math_percentage = passing_math / float(student_count) * 100
print("Percentage of students passing math:", passing_math_percentage)

Number of students passing math: 29370
Percentage of students passing math: 74.9808526933878

In [59]:
# Percentage of students passing reading
passing_reading = school_complete[(school_complete['reading_score'] >= 70)].count()["student_name"]
print("Number of students passing reading:", passing_reading)


passing_reading_percentage = passing_reading / float(student_count) * 100
print("Percentage of students passing reading:", passing_reading_percentage)

Number of students passing reading: 33610
Percentage of students passing reading: 85.80546336482001

In [57]:
# Percentage of students who passed math and reading
passing_students = school_complete[
    (school_complete['math_score'] >= 70) & (school_complete['reading_score'] >= 70)].count()['student_name']

print("Number of passing students:", passing_students)

total_passing_students = passing_students / float(student_count) * 100
print("Percentage of students passing:", total_passing_students)

Number of passing students: 25528
Percentage of students passing: 65.17232575950983

In [77]:
# creating the dataframe
# The pd.DataFrame is a fuction within Pandas that will allow you to create the new dataframe
# Using the functions that I calculated above I'm able to add it to a new dataframe that I labeled 'district_summary'
district_summary = pd.DataFrame({
    'Total Number of Unique Schools': [school_count],
    'Total Number of Students': [student_count],
    'Total Budget': [total_budget],
    'Average Math Score': [average_math_score],
    'Average Reading Score': [average_reading_score],
    '% Passing Math': [passing_math_percentage],
    '% Passing Reading': [passing_reading_percentage],
    'Overall % Passing': [total_passing_students]
})

#using the .map function I'm able to change the format on some of my data
# using the .applymap I'm able to change the format for multiple columns using one line of code
# Need to use a double square bracket when referencing multiple columns
district_summary["Total Number of Students"] = district_summary["Total Number of Students"].map("{:,}".format)
district_summary['Total Budget'] = district_summary['Total Budget']. map("{:,.2f}".format)
district_summary[['% Passing Math', '% Passing Reading', 'Overall % Passing']] = district_summary[['% Passing Math', '% Passing Reading', 'Overall % Passing']]. applymap("{:,.2f}%".format)

district_summary.head()

,Total Number of Unique Schools,Total Number of Students,Total Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,Overall % Passing
0,15,"39,170","24,649,428.00",78.985371,81.87784,74.98%,85.81%,65.17%

In [175]:
school_types = school_data.set_index(["school_name"])["type"]

school_name
Huang High School        District
Figueroa High School     District
Shelton High School       Charter
Hernandez High School    District
Griffin High School       Charter
Wilson High School        Charter
Cabrera High School       Charter
Bailey High School       District
Holden High School        Charter
Pena High School          Charter
Wright High School        Charter
Rodriguez High School    District
Johnson High School      District
Ford High School         District
Thomas High School        Charter
Name: type, dtype: object

In [308]:
school_names = school_data_complete['school_name'].unique()
# Calculating total student count
per_school_counts = school_data_complete["school_name"].value_counts()

In [309]:
# Calculate the total school budget and per capita spending
per_school_budget = school_data_complete.groupby(["school_name"]).mean()["budget"]
per_school_capita = per_school_budget / total_students

In [310]:
# Calculating the per school scores
per_school_math = school_data_complete.groupby(["school_name"]).mean()["math_score"]

per_school_reading = school_data_complete.groupby(["school_name"]).mean()["reading_score"]

In [160]:
# Calculate the number of schools with reading scores of 70 or higher and number of schools that passed math with 70 or higher
school_passing_reading = school_data_complete[(school_data_complete["reading_score"] >= 70)]

# Group by per school to shorten the data frame
per_school_passing_reading = school_passing_reading.groupby("school_name").count()["reading_score"]


school_passing_math = school_data_complete[(school_data_complete["math_score"] >= 70)]

# Group by per school to shorten the data frame
per_school_passing_math = school_passing_math.groupby("school_name").count()["math_score"]

In [311]:
# Calculate the number of schools that passed reading and math
passing_math_and_reading = school_data_complete[
    (school_data_complete["reading_score"] >= 70) & (school_data_complete["math_score"] >= 70)]

In [312]:
# Use the provided code to calculate the passing rates
per_school_passing_math = school_passing_math.groupby(["school_name"]).count()["student_name"] / total_students * 100
per_school_passing_reading = school_passing_reading.groupby(["school_name"]).count()["student_name"] / total_students * 100
overall_passing_rate = passing_math_and_reading.groupby(["school_name"]).count()["student_name"] / total_students * 100

per_school_passing_reading

school_name
Bailey High School       10.408476
Cabrera High School       4.603013
Figueroa High School      6.078632
Ford High School          5.545060
Griffin High School       3.640541
Hernandez High School     9.568547
Holden High School        1.049272
Huang High School         6.055655
Johnson High School       9.872351
Pena High School          2.356395
Rodriguez High School     8.189941
Shelton High School       4.309420
Thomas High School        4.061782
Wilson High School        5.626755
Wright High School        4.439622
Name: student_name, dtype: float64

In [313]:
# Creating the new data frame for the above calculations
# Removing the square brackets prevents the rows for displaying full lists of values
per_school_summary = pd.DataFrame({
    'School Name': school_names,
    'School Type': school_types,
    'Total Students': per_school_counts,
    'Per School Budget': per_school_budget,
    'Per Student Budget': per_school_capita,
    'Average Math Score': per_school_math,
    'Average Reading Score': per_school_reading,
    '% Passing Math': per_school_passing_math,
    '% Passing Reading': per_school_passing_reading,
    '% Overall Passing': overall_passing_rate
})

per_school_summary["Per School Budget"] = per_school_summary["Per School Budget"].map("${:,.2f}".format)
per_school_summary["Per Student Budget"] = per_school_summary["Per Student Budget"].map("${:,.2f}".format)
per_school_summary[['% Passing Math', '% Passing Reading', '% Overall Passing']] = per_school_summary[['% Passing Math', '% Passing Reading', '% Overall Passing']]. applymap("{:,.2f}%".format)

In [193]:
# Sorting the schools by '% Overall Passing' in descending order and displaying the top 5
top_schools = per_school_summary.sort_values("% Overall Passing", ascending=False)
top_schools.head(5)

,School Name,School Type,Total Students,Per School Budget,Per Student Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing
Bailey High School,Huang High School,District,4976,"$3,124,928.00",$79.78,77.048432,81.033963,8.47%,10.41%,6.94%
Johnson High School,Holden High School,District,4761,"$3,094,650.00",$79.01,77.072464,80.966394,8.03%,9.87%,6.51%
Hernandez High School,Wilson High School,District,4635,"$3,022,020.00",$77.15,77.289752,80.934412,7.90%,9.57%,6.33%
Rodriguez High School,Wright High School,District,3999,"$2,547,363.00",$65.03,76.842711,80.744686,6.78%,8.19%,5.41%
Wilson High School,Ford High School,Charter,2283,"$1,319,574.00",$33.69,83.274201,83.989488,5.47%,5.63%,5.28%

In [261]:
# Lowest performing schools bottom 5 worst
bottom_schools = per_school_summary.sort_values("% Overall Passing", ascending=True)
bottom_schools.head(5)

,School Name,School Type,Total Students,Per School Budget,Per Student Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing
Holden High School,Cabrera High School,Charter,427,"$248,087.00",$6.33,83.803279,83.814988,1.01%,1.05%,0.97%
Pena High School,Pena High School,Charter,962,"$585,858.00",$14.96,83.839917,84.044699,2.32%,2.36%,2.22%
Griffin High School,Griffin High School,Charter,1468,"$917,500.00",$23.42,83.351499,83.816757,3.50%,3.64%,3.40%
Ford High School,Hernandez High School,District,2739,"$1,763,916.00",$45.03,77.102592,80.746258,4.78%,5.55%,3.80%
Thomas High School,Johnson High School,Charter,1635,"$1,043,130.00",$26.63,83.418349,83.848930,3.89%,4.06%,3.80%

In [207]:
# Code used to separate the data by grade
ninth_graders = school_data_complete[(school_data_complete["grade"] == "9th")]
tenth_graders = school_data_complete[(school_data_complete["grade"] == "10th")]
eleventh_graders = school_data_complete[(school_data_complete["grade"] == "11th")]
twelfth_graders = school_data_complete[(school_data_complete["grade"] == "12th")]

ninth_graders.head()

,Student ID,student_name,gender,grade,school_name,reading_score,math_score,School ID,type,size,budget
0,0,Paul Bradley,M,9th,Huang High School,66,79,0,District,2917,1910635
4,4,Bonnie Ray,F,9th,Huang High School,97,84,0,District,2917,1910635
5,5,Bryan Miranda,M,9th,Huang High School,94,94,0,District,2917,1910635
12,12,Brittney Walker,F,9th,Huang High School,64,79,0,District,2917,1910635
13,13,William Long,M,9th,Huang High School,71,79,0,District,2917,1910635

In [263]:
# Groupby "school_name" and taking the average of each
ninth_graders_scores_math_grades = ninth_graders.groupby("school_name").mean()["math_score"]

tenth_graders_math_grades_math_grades = tenth_graders.groupby("school_name").mean()["math_score"]

eleventh_graders_math_grades = eleventh_graders.groupby("school_name").mean()["math_score"]

twelfth_graders_math_grades = twelfth_graders.groupby("school_name").mean()["math_score"]

In [264]:
# Reading scores

ninth_graders_scores_reading_grades = ninth_graders.groupby("school_name").mean()["reading_score"]

tenth_graders_reading_grades = tenth_graders.groupby("school_name").mean()["reading_score"]

eleventh_graders_reading_grades = eleventh_graders.groupby("school_name").mean()["reading_score"]

twelfth_graders_reading_grades = twelfth_graders.groupby("school_name").mean()["reading_score"]

In [272]:
# Creating the new dataframe for 'Reading scores by grade'
per_scores_by_grade = pd.DataFrame({
    '9th Grade Reading Scores': ninth_graders_scores_reading_grades,
    '10th Grade Reading Scores': tenth_graders_reading_grades,
    '11th Grade Reading Scores': eleventh_graders_reading_grades,
    '12th Grade Reading Scores': twelfth_graders_reading_grades
})

per_scores_by_grade

,9th Grade Reading Scores,10th Grade Reading Scores,11th Grade Reading Scores,12th Grade Reading Scores
school_name,,,,
Bailey High School,81.303155,80.907183,80.945643,80.912451
Cabrera High School,83.676136,84.253219,83.788382,84.287958
Figueroa High School,81.198598,81.408912,80.640339,81.384863
Ford High School,80.632653,81.262712,80.403642,80.662338
Griffin High School,83.369193,83.706897,84.288089,84.013699
Hernandez High School,80.866860,80.660147,81.396140,80.857143
Holden High School,83.677165,83.324561,83.815534,84.698795
Huang High School,81.290284,81.512386,81.417476,80.305983
Johnson High School,81.260714,80.773431,80.616027,81.227564
Pena High School,83.807273,83.612000,84.335938,84.591160
Rodriguez High School,80.993127,80.629808,80.864811,80.376426
Shelton High School,84.122642,83.441964,84.373786,82.781671
Thomas High School,83.728850,84.254157,83.585542,83.831361
Wilson High School,83.939778,84.021452,83.764608,84.317673
Wright High School,83.833333,83.812757,84.156322,84.073171

In [276]:
# Establish the bins 
spending_bins = [0, 585, 630, 645, 680]
labels = ["<$585", "$585-630", "$630-645", "$645-680"]

In [300]:
# Create a copy of school summary because it uses 'Per School Budget'
school_spending_df = per_school_summary.copy()

In [303]:
# Use `pd.cut` to categorize spending based on the bins
school_spending_df["Spending Ranges (Per Student)"] = pd.cut(per_school_capita, spending_bins, labels=labels)
school_spending_df

,School Name,School Type,Total Students,Per School Budget,Per Student Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing,Spending Ranges (Per Student)
Bailey High School,Huang High School,District,4976,"$3,124,928.00",$79.78,77.048432,81.033963,8.47%,10.41%,6.94%,<$585
Cabrera High School,Figueroa High School,Charter,1858,"$1,081,356.00",$27.61,83.061895,83.975780,4.47%,4.60%,4.33%,<$585
Figueroa High School,Shelton High School,District,2949,"$1,884,411.00",$48.11,76.711767,81.158020,4.97%,6.08%,4.01%,<$585
Ford High School,Hernandez High School,District,2739,"$1,763,916.00",$45.03,77.102592,80.746258,4.78%,5.55%,3.80%,<$585
Griffin High School,Griffin High School,Charter,1468,"$917,500.00",$23.42,83.351499,83.816757,3.50%,3.64%,3.40%,<$585
Hernandez High School,Wilson High School,District,4635,"$3,022,020.00",$77.15,77.289752,80.934412,7.90%,9.57%,6.33%,<$585
Holden High School,Cabrera High School,Charter,427,"$248,087.00",$6.33,83.803279,83.814988,1.01%,1.05%,0.97%,<$585
Huang High School,Bailey High School,District,2917,"$1,910,635.00",$48.78,76.629414,81.182722,4.89%,6.06%,3.99%,<$585
Johnson High School,Holden High School,District,4761,"$3,094,650.00",$79.01,77.072464,80.966394,8.03%,9.87%,6.51%,<$585
Pena High School,Pena High School,Charter,962,"$585,858.00",$14.96,83.839917,84.044699,2.32%,2.36%,2.22%,<$585
Rodriguez High School,Wright High School,District,3999,"$2,547,363.00",$65.03,76.842711,80.744686,6.78%,8.19%,5.41%,<$585
Shelton High School,Rodriguez High School,Charter,1761,"$1,056,600.00",$26.97,83.359455,83.725724,4.22%,4.31%,4.04%,<$585
Thomas High School,Johnson High School,Charter,1635,"$1,043,130.00",$26.63,83.418349,83.848930,3.89%,4.06%,3.80%,<$585
Wilson High School,Ford High School,Charter,2283,"$1,319,574.00",$33.69,83.274201,83.989488,5.47%,5.63%,5.28%,<$585
Wright High School,Thomas High School,Charter,1800,"$1,049,400.00",$26.79,83.682222,83.955000,4.29%,4.44%,4.15%,<$585

In [306]:
#  Calculate averages for the desired columns. 
spending_math_scores = school_spending_df.groupby(["Spending Ranges (Per Student)"]).mean()["Average Math Score"]

spending_reading_scores = school_spending_df.groupby(["Spending Ranges (Per Student)"]).mean()["Average Reading Score"]

In [307]:
spending_summary = pd.DataFrame({
    'Average Math Score': spending_math_scores,
    'Average Reading Score': spending_reading_scores
})
spending_summary

                               Average Math Score  Average Reading Score
Spending Ranges (Per Student)
<$585                                    80.43253              82.529188
$585-630                                      NaN                    NaN
$630-645                                      NaN                    NaN
$645-680                                      NaN                    NaN